import pandas as pd
import numpy as np
df = pd.read_csv("d:/csv/Employ_Data.csv")
print(df)
print('---------------------------------------------------')
table1=df.pivot(index=['Dept'], columns='Name',values='Salary')
print(table1)
# Department-wise total salary
dept_total = df.groupby("Dept")["Salary"].sum()
print("Dept-Wise Total Salary ")
print(dept_total)
print("Total Employees work in each dept")
dept_count = df.groupby("Dept")["Salary"].count()
print(dept_count)
print("Max Salary in Each Dept ")
max_sal = df.groupby("Dept")["Salary"].max()
print(max_sal)
print("Min Salary in Each Dept ")
min_sal = df.groupby("Dept")["Salary"].min()
print(min_sal)